# Generated by Django 5.0.6 on 2024-06-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday')], max_length=10)),
                ('start_time', models.CharField(choices=[('08.30 to 10.00', '08.30 to 10.00'), ('10.10 to 11.40', '10.10 to 11.40'), ('11.50 to 13.20', '11.50 to 13.20'), ('13.30 to 15.00', '13.30 to 15.00'), ('15.10 to 16.40', '15.10 to 16.40')], max_length=30)),
                ('module_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('group_name', models.CharField(max_length=100)),
                ('classroom_name', models.CharField(max_length=100)),
            ],
        ),
    ]
