# Generated by Django 5.0.6 on 2024-06-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time', '0002_remove_timetableslot_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableslot',
            name='start_time',
            field=models.CharField(choices=[('08.30 to 10.00', '08.30 to 10.00'), ('10.10 to 11.40', '10.10 to 11.40'), ('11.50 to 13.20', '11.50 to 13.20'), ('13.30 to 15.00', '13.30 to 15.00'), ('15.10 to 16.40', '15.10 to 16.40')], max_length=30),
        ),
    ]
