# Generated by Django 5.0.6 on 2024-06-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Time', '0003_alter_timetableslot_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableslot',
            name='day',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday')], max_length=10),
        ),
    ]
